# Site Settings
title: Adrian Strugala
url: 'https://adrianstrugala.github.io/'
baseurl: 'https://adrianstrugala.github.io/'

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Adrian Strugala
tagline: Software Developer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'I am a young and ambitious software developer and engineer of control engineering and robotics. I am open-minded and I am always looking for the newest technologies. Feel welcome to read about some of my newest projects.'

#sidebar links
email: strugala.adrian@gmail.com
phone: +48 791575951
#website: blog.webjeda.com #do not add http://
linkedin: adrian-strugala
github: adrianstrugala
#twitter: '@webjeda'
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
